### Basic Tutorial on RNN
#### Notebook Author: Nirupam Purushothama

**About:** Building a basic RNN using TensorFlow (barebones, does not use any of Tensorflow's RNN operations). Created in an unrolled fashion. That is both the timesteps are explicity called out and then operations are defined. Even inputs are segregated by the time-step

**Reference Book:** Hands-on Machine Learning with Scikit-Learn and TensorFlow - Aurelien Geron

**Network Shape**

X (+ Y) > 5 RNN-Neurons > Y

So, Y at t-1 is input to Neurons along with X

In [1]:
import tensorflow as tf

In [2]:
n_inputs = 3
n_neurons = 5

# Input at time t0
X0 = tf.placeholder(tf.float32, [None, n_inputs])

# Input at time t1
X1 = tf.placeholder(tf.float32, [None, n_inputs])

# Weights of X(same at all times)
Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))

# Weights of Y
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))

# Bias
b = tf.Variable(tf.zeros([1, n_neurons], dtype = tf.float32))

# Output at time t0
Y0 = tf.tanh(tf.matmul(X0, Wx) + b)

# Output at time t1
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()

In [3]:
import numpy as np

In [4]:
# Mini-batch: instance 0, instance 1, instance 2, instance 3
X0_batch = np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]]) # t = 0
X1_batch = np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]]) # t = 1

In [5]:
with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0,Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [6]:
print(Y0_val)

[[ 0.53749335 -0.99859637 -0.24833751  0.99999791 -0.8750518 ]
 [-0.99990845 -1.         -0.46882266  1.         -0.99999821]
 [-1.         -1.         -0.64312202  1.         -1.        ]
 [-1.         -1.         -0.99998403 -0.99723059 -1.        ]]


In [7]:
print(Y1_val)

[[-1.         -1.          0.04106434  1.         -1.        ]
 [-0.99967909  0.99450856 -0.69330305 -0.99852455  0.99963635]
 [-1.         -1.         -0.74034584  1.         -0.99997002]
 [-1.         -0.99945045 -0.99537706  0.99648243 -0.98805767]]


**Note:** If we have to write it the same way for 100 time-steps then the code will become humongous and the graph will also become too big.

So, we better use TensorFlow's RNN operations