### Basic Tutorial on RNN - 3
#### Notebook Author: Nirupam Purushothama

**About:** Building a basic RNN using TensorFlow (barebones). Created using TensorFlow RNN functions

Static unrolling through time - But input also provided as a batch input

**Reference Book:** Hands-on Machine Learning with Scikit-Learn and TensorFlow - Aurelien Geron

In [1]:
import tensorflow as tf

In [2]:
n_inputs = 3 # Number of inputs per mini-batch
n_steps = 2 # Number of time steps
n_neurons = 5 # Number of neurons

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])

# tf.transpose
X_seqs = tf.unstack(tf.transpose(X, perm=[1,0,2]))

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units = n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, X_seqs, dtype=tf.float32)

# Gets the output into [None, n_steps, n_inputs] shape
outputs = tf.transpose(tf.stack(output_seqs), perm=[1,0,2])

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.


In [3]:
import numpy as np

In [4]:
# Mini-batch: instance 0, instance 1, instance 2, instance 3
X_batch = np.array([
    [[0,1,2],[9,8,7]],
    [[3,4,5],[0,0,0]],
    [[6,7,8],[6,5,4]],
    [[9,0,1],[3,2,1]],    
])

init = tf.global_variables_initializer()

In [5]:
# Understanding the transpose function. perm - The type of permutation you would require.
# Below print is self-explanatory

z = tf.transpose(X_batch, perm=[1,0,2])
print(X_batch.shape)
print(z.shape)

(4, 2, 3)
(2, 4, 3)


In [6]:
with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [7]:
print(outputs_val)

[[[ 0.89812666  0.5646168  -0.28691128  0.84830683  0.07136286]
  [ 0.98208904  0.99992794 -0.99999934  0.98900819 -0.9992702 ]]

 [[ 0.99428833  0.98352897 -0.99286908  0.99106401 -0.72675556]
  [-0.89091104  0.53958696 -0.21682814 -0.49988967 -0.79737538]]

 [[ 0.99969435  0.99950439 -0.99995381  0.99950927 -0.95751303]
  [-0.05265796  0.99823546 -0.99989027  0.77930015 -0.99560475]]

 [[-0.99970752  0.99763662 -0.9958359  -0.34800643 -0.99767113]
  [-0.70426148  0.47066903 -0.98827076  0.62712705 -0.78638566]]]


#### But this still creates one cell per step (internally) and the graph constructed will be huge and will generate out of memory errors. Hence we use Dynamic RNNs