### Dynamic RNN - Extension of Static RNN
#### Notebook Author: Nirupam Purushothama

**About:** Dynamic unrolling through time
* Uses while_loop() to run over the cell approprite number of times
* Can swap GPU memory to CPU memory 
* Accepts a single tensor for all inputs at every timestep 
* Outputs a single tensor for all outputs at every timestep
* No need to stack/unstack/transpose

**Reference Book:** Hands-on Machine Learning with Scikit-Learn and TensorFlow - Aurelien Geron

In [2]:
import tensorflow as tf

In [4]:
n_inputs = 3 # Number of inputs per mini-batch
n_steps = 2 # Number of time steps
n_neurons = 5 # Number of neurons

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units = n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

In [5]:
import numpy as np

In [6]:
# Mini-batch: instance 0, instance 1, instance 2, instance 3
X_batch = np.array([
    [[0,1,2],[9,8,7]],
    [[3,4,5],[0,0,0]],
    [[6,7,8],[6,5,4]],
    [[9,0,1],[3,2,1]],    
])

init = tf.global_variables_initializer()

In [7]:
with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [8]:
print(outputs_val)

[[[-0.17320856 -0.81279624 -0.85754395  0.62516659 -0.24488541]
  [-0.56728691 -0.99894196 -1.         -0.8792392   0.9999966 ]]

 [[-0.32289252 -0.9949863  -0.99992627  0.6759342   0.93173778]
  [ 0.12957698  0.26272017 -0.85935092 -0.80255032  0.82559961]]

 [[-0.45799682 -0.99987763 -1.          0.72100621  0.99848628]
  [ 0.04570349 -0.98267627 -0.99999964 -0.93722802  0.99994427]]

 [[ 0.98467076  0.96808958 -0.99687892 -0.93579489  0.99946827]
  [-0.31260675 -0.80486101 -0.99101067 -0.10424052  0.99520844]]]


#### Unlike StaticRNN, here a while_loop goes over the time steps and stores the tensor values for each iteration during the forward pass so that it can use them to compute the gradients during the reverse pass